/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xy_lr_java_jni_ShellDemo */

#ifndef _Included_com_xy_lr_java_jni_ShellDemo
#define _Included_com_xy_lr_java_jni_ShellDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xy_lr_java_jni_ShellDemo
 * Method:    execShell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xy_lr_java_jni_ShellDemo_execShell
  (JNIEnv *, jobject);

/*
 * Class:     com_xy_lr_java_jni_ShellDemo
 * Method:    execChineseProcessor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xy_lr_java_jni_ShellDemo_execChineseProcessor
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
