/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xy_lr_java_jni_FirstDemo */

#ifndef _Included_com_xy_lr_java_jni_FirstDemo
#define _Included_com_xy_lr_java_jni_FirstDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xy_lr_java_jni_FirstDemo
 * Method:    getNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xy_lr_java_jni_FirstDemo_getNum
  (JNIEnv *, jobject);

/*
 * Class:     com_xy_lr_java_jni_FirstDemo
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xy_lr_java_jni_FirstDemo_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
