/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xy_lr_java_jni_ChineseInfoXtract4j */

#ifndef _Included_com_xy_lr_java_jni_ChineseInfoXtract4j
#define _Included_com_xy_lr_java_jni_ChineseInfoXtract4j
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xy_lr_java_jni_ChineseInfoXtract4j
 * Method:    ChineseProcessor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xy_lr_java_jni_ChineseInfoXtract4j_ChineseProcessor
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
